In [17]:
import numpy as np
import pandas as pd

In [42]:
revenue_data = {
    "2018" :  [180,200,220],
    "2019" : [24,36,40],
    "2020" : [12,18,20]   
}
revenue = pd.DataFrame(revenue_data,
                      index = ['Iphone','Ipad','Mac'])

In [43]:
expenses_data = {
        "2018" :  [80,90,100],
    "2019" : [10,16,20],
    "2020" : [8,10,10]
}
expenses = pd.DataFrame(expenses_data, index = ['Iphone','Ipad','Mac'])

In [44]:
revenue

2018  2019  2020
Iphone   180    24    12
Ipad     200    36    18
Mac      220    40    20

In [45]:
expenses

2018  2019  2020
Iphone    80    10     8
Ipad      90    16    10
Mac      100    20    10

In [2]:
revenue  = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses  = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [4]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [8]:
price_per_unit = np.array([1000,400,1200])
units_sold = np.array([[30,40,50],[5,10,15],[2,5,15]])

In [13]:
units_sold

array([[30, 40, 50],
       [ 5, 10, 15],
       [ 2,  5, 15]])

In [14]:
price_per_unit

array([1000,  400, 1200])

### Broadcasting

In [15]:
price_per_unit*units_sold   

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000, 18000]])

## Let us now Calculate Dot Product

In [16]:
np.dot(price_per_unit,units_sold)   # price_per_unit * first column of units_sold , For year [2018,2019,2020]

array([34400, 50000, 74000])

In [47]:
price_per_unit

array([1000,  400, 1200])

In [48]:
units_sold

array([[30, 40, 50],
       [ 5, 10, 15],
       [ 2,  5, 15]])

### For 2018 it does this 

In [49]:
(30*1000)+(5*400)+(2*1200)

34400

### For 2018 it does this 

In [50]:
(40*1000)+(10*400)+(5*1200)

50000

### For 2018 it does this 

In [51]:
(50*1000)+(15*400)+(15*1200)

74000

## Practice Questions

In [53]:
data  = {
    "2018" : [200,68,110,80],
    "2019" : [220,79,140,85],
    "2020" : [250,105,180,90]
}
indian_companies_revenue_in_Dollars = pd.DataFrame(data,index=["Reliance Industries","Infosys","TCS","Wipro"])

In [54]:
indian_companies_revenue_in_Dollars

2018  2019  2020
Reliance Industries   200   220   250
Infosys                68    79   105
TCS                   110   140   180
Wipro                  80    85    90

In [57]:
# Assuming 1USD =75 INR
INR = [75,75,75,75]

In [58]:
indian_companies_revenue_in_Dollars = np.dot(INR,indian_companies_revenue_in_Dollars)

In [59]:
indian_companies_revenue_in_Dollars

array([34350, 39300, 46875], dtype=int64)